import type { CoachmarkStep } from '@/components/Coachmark';

export const coachmarkSteps: CoachmarkStep[] = [
  // Clients Page Steps (home / start here)
  {
    id: 'clients-nav',
    targetSelector: 'clients-nav',
    title: 'Manage Clients',
    description: 'Start here. Add your clients — you\'ll need at least one before creating contracts.',
    position: 'bottom',
    targetPage: 'clients',
  },
  {
    id: 'add-client-btn',
    targetSelector: 'add-client-btn',
    title: 'Add a Client',
    description: 'Click this button to add a new client. Enter their company name, address, and email.',
    position: 'bottom',
    targetPage: 'clients',
  },
  {
    id: 'client-form',
    targetSelector: 'client-form',
    title: 'Client Form',
    description: 'Fill in the client details. Company Name is required. Click Create when done.',
    position: 'top',
    targetPage: 'clients',
    waitForElement: true,
  },
  {
    id: 'contracts-under-clients',
    targetSelector: 'clients-nav',
    title: 'Contracts live under Clients',
    description: 'Open a client, then add contracts there. Contracts define recurring services used to generate invoices.',
    position: 'bottom',
    targetPage: 'clients',
  },
  // Settings via More menu
  {
    id: 'more-nav',
    targetSelector: 'more-nav',
    title: 'More',
    description: 'Settings, Backup, Privacy, and help live under More. Open it when you need those tools.',
    position: 'bottom',
    targetPage: 'clients',
  },
  {
    id: 'settings-nav',
    targetSelector: 'settings-nav',
    title: 'Settings',
    description: 'Configure your freelancer information and bank details. Open More → Settings to get started.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'freelancer-info',
    targetSelector: 'freelancer-info-card',
    title: 'Freelancer Information',
    description: 'Fill in your name, address, and email. This information will appear on all your invoices.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'bank-details',
    targetSelector: 'bank-details-card',
    title: 'Bank Details',
    description: 'Enter your bank information for payment remittance. This will be shown on invoice PDFs.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'filename-template',
    targetSelector: 'filename-template-input',
    title: 'PDF Filename Template',
    description: 'Customize how your invoice PDFs are named. Use tokens like {client}, {year}, {month} for dynamic filenames.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'save-settings',
    targetSelector: 'save-settings-btn',
    title: 'Save Your Settings',
    description: 'Click Save Settings to store your information. You can update these anytime.',
    position: 'top',
    targetPage: 'settings',
  },
  // Invoices Page Steps
  {
    id: 'invoices-nav',
    targetSelector: 'invoices-nav',
    title: 'Browse Invoices',
    description: 'View all invoices here. To generate or create invoices: Clients → open client → open contract.',
    position: 'bottom',
    targetPage: 'invoices',
  },
  {
    id: 'invoice-table',
    targetSelector: 'invoice-table',
    title: 'Invoice List',
    description: 'View all your invoices here. You can preview and download PDFs. Generation and deletion happen from a contract.',
    position: 'top',
    targetPage: 'invoices',
  },
  {
    id: 'preview-btn',
    targetSelector: 'preview-btn',
    title: 'Preview Invoice',
    description: 'Click Preview to see how your invoice PDF looks before downloading. Great for checking the format.',
    position: 'left',
    targetPage: 'invoices',
    waitForElement: true,
  },
  // Backup Page Steps
  {
    id: 'backup-nav',
    targetSelector: 'backup-nav',
    title: 'Backup Your Data',
    description: 'Regularly export your data to keep it safe. Open More → Backup. All data is stored locally in your browser.',
    position: 'bottom',
    targetPage: 'backup',
  },
  {
    id: 'export-btn',
    targetSelector: 'export-btn',
    title: 'Export Data',
    description: 'Click to download all your data as a JSON file. Keep this file safe - you can import it later to restore everything.',
    position: 'bottom',
    targetPage: 'backup',
  },
  {
    id: 'import-input',
    targetSelector: 'import-input',
    title: 'Import Data',
    description: 'Select a previously exported JSON file to restore all your data. This will replace your current data.',
    position: 'top',
    targetPage: 'backup',
  },
];
