import type { CoachmarkStep } from '@/components/Coachmark';

export const coachmarkSteps: CoachmarkStep[] = [
  // Settings Page Steps
  {
    id: 'settings-nav',
    targetSelector: 'settings-nav',
    title: 'Start with Settings',
    description: 'First, configure your freelancer information and bank details. Click on Settings to get started.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'freelancer-info',
    targetSelector: 'freelancer-info-card',
    title: 'Freelancer Information',
    description: 'Fill in your name, address, and email. This information will appear on all your invoices.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'bank-details',
    targetSelector: 'bank-details-card',
    title: 'Bank Details',
    description: 'Enter your bank information for payment remittance. This will be shown on invoice PDFs.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'filename-template',
    targetSelector: 'filename-template-input',
    title: 'PDF Filename Template',
    description: 'Customize how your invoice PDFs are named. Use tokens like {client}, {year}, {month} for dynamic filenames.',
    position: 'bottom',
    targetPage: 'settings',
  },
  {
    id: 'save-settings',
    targetSelector: 'save-settings-btn',
    title: 'Save Your Settings',
    description: 'Click Save Settings to store your information. You can update these anytime.',
    position: 'top',
    targetPage: 'settings',
  },
  // Clients Page Steps
  {
    id: 'clients-nav',
    targetSelector: 'clients-nav',
    title: 'Manage Clients',
    description: 'Add your clients here. You\'ll need at least one client before creating contracts.',
    position: 'bottom',
    targetPage: 'clients',
  },
  {
    id: 'add-client-btn',
    targetSelector: 'add-client-btn',
    title: 'Add a Client',
    description: 'Click this button to add a new client. Enter their company name, address, and email.',
    position: 'bottom',
    targetPage: 'clients',
  },
  {
    id: 'client-form',
    targetSelector: 'client-form',
    title: 'Client Form',
    description: 'Fill in the client details. Company Name is required. Click Create when done.',
    position: 'top',
    targetPage: 'clients',
    waitForElement: true,
  },
  // Contracts Page Steps
  {
    id: 'contracts-nav',
    targetSelector: 'contracts-nav',
    title: 'Create Contracts',
    description: 'Contracts define recurring services for your clients. They\'re used to automatically generate invoices.',
    position: 'bottom',
    targetPage: 'contracts',
  },
  {
    id: 'add-contract-btn',
    targetSelector: 'add-contract-btn',
    title: 'Add a Contract',
    description: 'Click to create a new contract. You\'ll need to select a client and define service details.',
    position: 'bottom',
    targetPage: 'contracts',
  },
  {
    id: 'contract-client-select',
    targetSelector: 'contract-client-select',
    title: 'Select Client',
    description: 'Choose the client for this contract. Make sure you\'ve added clients first.',
    position: 'bottom',
    targetPage: 'contracts',
    waitForElement: true,
  },
  {
    id: 'contract-description',
    targetSelector: 'contract-description-input',
    title: 'Description Template',
    description: 'Enter service description. Use {{month}} and {{year}} placeholders - they\'ll be replaced with actual dates in invoices.',
    position: 'bottom',
    targetPage: 'contracts',
    waitForElement: true,
  },
  // Invoices Page Steps
  {
    id: 'invoices-nav',
    targetSelector: 'invoices-nav',
    title: 'Generate Invoices',
    description: 'Once you have contracts, you can generate invoices for the entire year with one click.',
    position: 'bottom',
    targetPage: 'invoices',
  },
  {
    id: 'generate-invoices-btn',
    targetSelector: 'generate-invoices-btn',
    title: 'Generate Invoices',
    description: 'Click this button to automatically create 12 monthly invoices for all your contracts. Existing invoices will be skipped.',
    position: 'bottom',
    targetPage: 'invoices',
  },
  {
    id: 'invoice-table',
    targetSelector: 'invoice-table',
    title: 'Invoice List',
    description: 'View all your generated invoices here. You can preview, download PDFs, or delete invoices.',
    position: 'top',
    targetPage: 'invoices',
  },
  {
    id: 'preview-btn',
    targetSelector: 'preview-btn',
    title: 'Preview Invoice',
    description: 'Click Preview to see how your invoice PDF looks before downloading. Great for checking the format.',
    position: 'left',
    targetPage: 'invoices',
    waitForElement: true,
  },
  // Backup Page Steps
  {
    id: 'backup-nav',
    targetSelector: 'backup-nav',
    title: 'Backup Your Data',
    description: 'Regularly export your data to keep it safe. All data is stored locally in your browser.',
    position: 'bottom',
    targetPage: 'backup',
  },
  {
    id: 'export-btn',
    targetSelector: 'export-btn',
    title: 'Export Data',
    description: 'Click to download all your data as a JSON file. Keep this file safe - you can import it later to restore everything.',
    position: 'bottom',
    targetPage: 'backup',
  },
  {
    id: 'import-input',
    targetSelector: 'import-input',
    title: 'Import Data',
    description: 'Select a previously exported JSON file to restore all your data. This will replace your current data.',
    position: 'top',
    targetPage: 'backup',
  },
];
